#!/usr/bin/sh

exec 1>&2

cmake_version="$(sed -nE '/^project/s/.* VERSION ([0-9.]+) .*/\1/p' CMakeLists.txt)"

if [ -z "${cmake_version}" ]
then
    echo -e "\e[1;31mVersion is not specified in CMakeLists.txt\e[0m"
    exit 2
fi

while read local_ref local_sha remote_ref remote_sha
do
    case "${remote_ref}" in
        refs/tags/*)
            tag_name="${remote_ref#refs/tags/}"
            tag_version="$(echo "${tag_name}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"

            if [ -z "${tag_version}" ]
            then
                continue
            fi

            if [ "${tag_version}" != "${cmake_version}" ]
            then
                echo -e "\e[1;31mTag '${tag_name}' version (${tag_version}) does not match project version in CMakeLists.txt (${cmake_version})\e[0m"
                exit 3
            fi
            ;;
    esac
done
