name: release
on:
  push:
    branches:
      - release/*
    tags:
      - v*
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install --yes --no-install-recommends libwebkit2gtk-4.1-dev libayatana-appindicator3-1 libgtk-3-dev openjdk-21-jdk openjdk-21-jdk-headless
      - name: Build
        run: cargo tauri build
  release:
    needs: build-linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - run: cargo tauri build
      - run: cargo tauri publish
